### ISSUE TITLE
6.7版本的报错

### ISSUE THREAD

**Issue by 276523923** [anbai-inc/Kibana_Hanization#45]
已经复制过去，但是启动的时候报错了。
Mac下的，使用brew安装的 kibana

[03:57:29.391] [fatal][root] Error: [I18n] Error formatting message: "kbn.advancedSettings.query.queryStringOptionsText" for locale: "zh_cn".
Error: The intl string context variable 'queryLanguage' was not provided to the string 'lucene 查询字符串分析器的{optionsLink}。仅将“{queryLanguage}”设置为 {luceneLanguage} 时才会使用。'
    at Object.translate (/usr/local/Cellar/kibana/6.7.0/node_modules/@kbn/i18n/target/node/core/i18n.js:209:13)
    at getUiSettingDefaults (/usr/local/Cellar/kibana/6.7.0/src/legacy/core_plugins/kibana/ui_setting_defaults.js:39:31)
    at Object.<anonymous> (/usr/local/Cellar/kibana/6.7.0/src/legacy/core_plugins/kibana/server/lib/kql_usage_collector/fetch.js:32:73)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/Cellar/kibana/6.7.0/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/Cellar/kibana/6.7.0/src/legacy/core_plugins/kibana/server/lib/kql_usage_collector/make_kql_usage_collector.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/Cellar/kibana/6.7.0/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/Cellar/kibana/6.7.0/src/legacy/core_plugins/kibana/server/lib/kql_usage_collector/index.js:7:33)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

 FATAL  Error: [I18n] Error formatting message: "kbn.advancedSettings.query.queryStringOptionsText" for locale: "zh_cn".
Error: The intl string context variable 'queryLanguage' was not provided to the string 'lucene 查询字符串分析器的{optionsLink}。仅将“{queryLanguage}”设置为 {luceneLanguage} 时才会使用。'

**Comment by chachabu** [comment]
我是tar 安装 centos 下的  6.7.1 报了同样的错误
